### ISSUE TITLE
Water bending from Cauldron

### ISSUE THREAD

**Issue by JavyQuavy** [saperate/Elementals#1]
When water bending from a cauldron, the cauldron disappears.

**Comment by saperate** [comment]
Yeah i got started on adding waterlogged blocks to water bendable blocks and i didn't finish, i'll try to make it work today

**Comment by saperate** [comment]
Turns out cauldrons are not waterloggable, i thought that was how they stored fluids but i was wrong. There should be a fix for this issue by the end of the day, so stay tuned for that

**Comment by saperate** [comment]
fixed in 1.0.10, thank you for the bug report :)
https://modrinth.com/mod/elemental/version/zAriLELe
