### ISSUE TITLE
Fire bending works underwater

### ISSUE THREAD

**Issue by Lycanroc9** [saperate/Elementals#2]
(I think this is the right place to mention a bug) I was testing your mod (it's really good, best mod I've ever played) I was testing fire bending and it seemed to work underwater. In Avatar fire benders can't bend fire in water, maybe you could add an ability that allows fire benders to make like steam/vapor underwater that could damage players but also possibly each other? Thank you. (I really love this mod! Keep up the good work!)

**Comment by saperate** [comment]
woops, it seems like i didn't see your issue for a while, sorry about that. when i find the time i'll fix this. Thank you for the kind words and for reporting this :)

**Comment by saperate** [comment]
fixed in 1.0.37
