### ISSUE TITLE
Fire bending attacks aren't registered as being done by the player

### ISSUE THREAD

**Issue by Dashy22** [saperate/Elementals#4]
When I hit a mob with a fire attack and it dies on it's on by my fire then it doesn't count toward the elemental experience so I'm getting practically no kills technically since the afterburn of fire is whats killing the mob. And because of I-Frames. I cant really kill the mob when it's on fire.

**Comment by saperate** [comment]
Ok so, it is indeed a bug that fire attacks aren't registered as  being done by the player, but it still does give you experience. As you use chi, you proportionally gain experience

**Comment by Dashy22** [comment]
oh ok I thought it was if you kill something you gain experience, because it was just pretty slow when using fire

**Comment by saperate** [comment]
fixed in 1.0.35
