### ISSUE TITLE
no creative flight after pressing v underwater while sprinting (surf)

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [saperate/Elementals#5]
after swimming and stopping creative flight stops working. (until you switch gamemodes and switch back)

**Comment by OrdinaryCloverOC** [comment]
i can't seem to reproduce this, so if anyone does further testing let the mod author know

**Comment by saperate** [comment]
I can' really verify it right now, but i think i know why this would happen. I'll try fixing it in the next update. Thanks for the report :)

**Comment by saperate** [comment]
Verified as a bug, and fixed in 1.0.37
